baseurl = "https://threearrowsec.github.io/tas.com/"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-code-editor-theme"
publishDir = "docs"

[params]
    author = "John Doe"
    locale = "en-US"
